export default [
  {
    slug: "cooling-fans",
    permalink: "sun-travel-cooling-fans.html",
    pageTitle: "Cooling & Fans",
    metaDescription: "Portable cooling gear and fans for hot park days — curated Amazon picks from The Pixie Packed Family.",
    backLinkHref: "sun-travel-essentials.html",
    backLinkLabel: "← Back to Sun, Travel & Personal Care",
    eyebrow: "Shop the Parks",
    heroTitle: "Cooling &amp; Fans",
    heroSubtitle: "Portable ways to beat the Florida heat, from handheld fans to stroller-mounted misters.",
    hasSectionHeader: false,
    hasSubgroups: false
  },
  {
    slug: "womens",
    permalink: "apparel-womens.html",
    pageTitle: "Women's Apparel",
    metaDescription: "Women's Disney apparel, tees, and loungewear — curated Amazon picks from The Pixie Packed Family.",
    backLinkHref: "apparel.html",
    backLinkLabel: "← Back to Apparel",
    eyebrow: "Shop the Parks",
    heroTitle: "Women's",
    heroSubtitle: "Disney-inspired tees, tanks, shorts, and comfy loungewear for mom.",
    hasSectionHeader: false,
    hasSubgroups: false
  },
  {
    slug: "loungefly",
    permalink: "accessories-loungefly.html",
    pageTitle: "Loungefly",
    metaDescription: "Disney Loungefly backpacks and wallets — curated Amazon picks from The Pixie Packed Family.",
    backLinkHref: "accessories.html",
    backLinkLabel: "← Back to Accessories",
    eyebrow: "Park Day Accessories",
    heroTitle: "Loungefly",
    heroSubtitle: "Collectible mini backpacks and wallets for the Disney lover in your family.",
    hasSectionHeader: true,
    sectionId: "loungefly",
    catTitle: "Loungefly",
    catSub: "Collectible mini backpacks and wallets for the Disney lover in your family.",
    hasSubgroups: true,
    subgroupOrder: ["loungefly-backpacks", "loungefly-wallets"],
    subgroupLabels: { "loungefly-backpacks": "Backpacks", "loungefly-wallets": "Wallets" }
  },
  {
    slug: "hats",
    permalink: "accessories-hats.html",
    pageTitle: "Hats",
    metaDescription: "Sun hats and caps for Disney park days — curated Amazon picks from The Pixie Packed Family.",
    backLinkHref: "accessories.html",
    backLinkLabel: "← Back to Accessories",
    eyebrow: "Park Day Accessories",
    heroTitle: "Hats",
    heroSubtitle: "Sun protection with a little extra park-day personality.",
    hasSectionHeader: true,
    sectionId: "hats",
    catTitle: "Hats",
    catSub: "Sun protection with a little extra park-day personality.",
    hasSubgroups: false
  },
  {
    slug: "ears-headbands",
    permalink: "accessories-ears-headbands.html",
    pageTitle: "Ears &amp; Headbands",
    metaDescription: "Minnie ears and headbands for Disney park days — curated Amazon picks from The Pixie Packed Family.",
    backLinkHref: "accessories.html",
    backLinkLabel: "← Back to Accessories",
    eyebrow: "Park Day Accessories",
    heroTitle: "Ears &amp; Headbands",
    heroSubtitle: "The finishing touch on any park outfit.",
    hasSectionHeader: true,
    sectionId: "ears",
    catTitle: "Ears &amp; Headbands",
    catSub: "The finishing touch on any park outfit.",
    hasSubgroups: false
  },
  {
    slug: "pandora",
    permalink: "accessories-pandora.html",
    pageTitle: "Pandora",
    metaDescription: "Disney Pandora charms and bracelets — curated Amazon picks from The Pixie Packed Family.",
    backLinkHref: "accessories.html",
    backLinkLabel: "← Back to Accessories",
    eyebrow: "Park Day Accessories",
    heroTitle: "Pandora",
    heroSubtitle: "Charms and bracelets to build a Disney story piece by piece.",
    hasSectionHeader: true,
    sectionId: "pandora",
    catTitle: "Pandora",
    catSub: "Charms and bracelets to build a Disney story piece by piece.",
    hasSubgroups: false
  },
  {
    slug: "footwear",
    permalink: "accessories-footwear.html",
    pageTitle: "Footwear",
    metaDescription: "Park-tested shoes for Disney vacations — curated Amazon picks from The Pixie Packed Family.",
    backLinkHref: "accessories.html",
    backLinkLabel: "← Back to Accessories",
    eyebrow: "Park Day Accessories",
    heroTitle: "Footwear",
    heroSubtitle: "Comfortable, park-tested shoes for all-day walking.",
    hasSectionHeader: true,
    sectionId: "footwear",
    catTitle: "Footwear",
    catSub: "Comfortable, park-tested shoes for all-day walking.",
    hasSubgroups: true,
    subgroupOrder: ["footwear-mens", "footwear-womens"],
    subgroupLabels: { "footwear-mens": "Men's", "footwear-womens": "Women's" }
  },
  {
    slug: "family-tees",
    permalink: "apparel-family-tees.htm",
    pageTitle: "Matching Family Tees",
    metaDescription: "Matching family tee sets for Disney vacations — curated Amazon picks from The Pixie Packed Family.",
    backLinkHref: "apparel.html",
    backLinkLabel: "← Back to Apparel",
    eyebrow: "Shop the Parks",
    heroTitle: "Matching Family Tees",
    heroSubtitle: "Coordinated park-day outfits the whole crew will actually want to wear.",
    hasSectionHeader: false,
    hasSubgroups: false
  },
  {
    slug: "mens",
    permalink: "apparel-mens.html",
    pageTitle: "Men's Apparel",
    metaDescription: "Men's Disney apparel and shorts — curated Amazon picks from The Pixie Packed Family.",
    backLinkHref: "apparel.html",
    backLinkLabel: "← Back to Apparel",
    eyebrow: "Shop the Parks",
    heroTitle: "Men's",
    heroSubtitle: "Disney apparel and shorts for dad.",
    hasSectionHeader: false,
    hasSubgroups: false
  },
  {
    slug: "kids",
    permalink: "apparel-kids.html",
    pageTitle: "Kids' Apparel",
    metaDescription: "Disney apparel for kids — curated Amazon picks from The Pixie Packed Family.",
    backLinkHref: "apparel.html",
    backLinkLabel: "← Back to Apparel",
    eyebrow: "Shop the Parks",
    heroTitle: "Kids",
    heroSubtitle: "Disney apparel for the little ones.",
    hasSectionHeader: false,
    hasSubgroups: false
  },
  {
    slug: "sunscreen",
    permalink: "sun-travel-sunscreen.html",
    pageTitle: "Sunscreen",
    metaDescription: "Sunscreen picks for Disney parks and family trips — curated Amazon picks from The Pixie Packed Family.",
    backLinkHref: "sun-travel-essentials.html",
    backLinkLabel: "← Back to Sun, Travel & Personal Care",
    eyebrow: "Shop the Parks",
    heroTitle: "Sunscreen",
    heroSubtitle: "Broad-spectrum protection for every member of the family, from lips to scalp.",
    hasSectionHeader: false,
    hasSubgroups: false
  },
  {
    slug: "hair-care",
    permalink: "sun-travel-hair-care.html",
    pageTitle: "Hair Care",
    metaDescription: "Frizz-fighting and detangling hair care for humid park days — curated Amazon picks from The Pixie Packed Family.",
    backLinkHref: "sun-travel-essentials.html",
    backLinkLabel: "← Back to Sun, Travel & Personal Care",
    eyebrow: "Shop the Parks",
    heroTitle: "Hair Care",
    heroSubtitle: "Frizz-fighting, detangling, and styling essentials for humid park days and post-swim hair.",
    hasSectionHeader: false,
    hasSubgroups: false
  },
  {
    slug: "personal-care",
    permalink: "sun-travel-personal-care.html",
    pageTitle: "Travel &amp; Personal Care",
    metaDescription: "Travel-size personal care essentials for Disney vacations — curated Amazon picks from The Pixie Packed Family.",
    backLinkHref: "sun-travel-essentials.html",
    backLinkLabel: "← Back to Sun, Travel & Personal Care",
    eyebrow: "Shop the Parks",
    heroTitle: "Travel &amp; Personal Care",
    heroSubtitle: "Travel-size personal care essentials to keep everyone fresh and comfortable on long park days.",
    hasSectionHeader: false,
    hasSubgroups: false
  },
  {
    slug: "family-halloween",
    permalink: "holidays-family-halloween.html",
    pageTitle: "Family Halloween / MNSSHP",
    metaDescription: "Spooky-cute matching looks for Mickey's Not-So-Scary Halloween Party and family Halloween fun — curated Amazon picks from The Pixie Packed Family.",
    backLinkHref: "holidays.html",
    backLinkLabel: "← Back to Holidays",
    eyebrow: "Holidays &amp; Festivals",
    heroTitle: "Family Halloween / MNSSHP",
    heroSubtitle: "Spooky-cute matching looks for Mickey's Not-So-Scary Halloween Party and family Halloween fun.",
    hasSectionHeader: false,
    hasSubgroups: true,
    subgroupOrder: ["halloween-unisex", "halloween-womens", "halloween-youth"],
    subgroupLabels: { "halloween-unisex": "Unisex", "halloween-womens": "Women's", "halloween-youth": "Youth" }
  }
];
